article: flashfest expansion
MOD-Magazine/MOD-Magazine pull request #21
Opened 2023-04-23 17:30 UTC by Jamalam360

This expands the flashfest article to include information about the submissions, since the news section is being deprecated in #12.

@sschr15 this PR contains information about your mod, you may want to check it.

closes: #7 

This article has frontmatter according to #12 so should not be merged before #12 is merged.

2023-04-23 17:33 UTC, sschr15 approved these changes

2023-04-23 17:51 UTC, SylvKT requested changes

2023-04-23 17:51 UTC, SylvKT commented on April23/flashfest.md
Unobtanium needs an accompanying image

2023-04-23 17:53 UTC, Jamalam360 commented on April23/flashfest.md
That's fine, but I couldn't find one

2023-04-23 17:54 UTC, SylvKT commented on April23/flashfest.md
I believe it’s in the flash fest showcase channel

2023-04-23 17:59 UTC, Jamalam360 commented on April23/flashfest.md
Ah yes, I forgot the video was there, I can just grab an image from there.

Thank you for the review

2023-04-23 19:54 UTC, Jamalam360 commented
This is good to be merged once #19 and #12 are

2023-04-23 20:16 UTC, SylvKT commented on April23/assets/unobtanium.png
good enough imo

2023-04-23 20:16 UTC, SylvKT approved these changes

2023-04-25 14:12 UTC, Jamalam360 commented
This can be merged after #12 and #19

2023-05-03 11:54 UTC, merged